[workspace]
resolver = "3"
members = ["core", "config", "utility"]
default-members = ["core"]

[workspace.dependencies]
axum = "0.8.9"
toml = "1.1.2"
tracing = "0.1.44"
serde_json = "1.0"
futures-util = "0.3"
tokio-tungstenite = "0.24"

[workspace.dependencies.config]
path = "config"

[workspace.dependencies.utility]
path = "utility"

[workspace.dependencies.serde]
version = "1.0.228"
features = [ "derive" ]

[workspace.dependencies.tokio]
version = "1.52.1"
features = ["macros", "rt-multi-thread"]

[workspace.package]
publish = false
edition = "2024"
