[[bin]]
name = "bwnli"
path = "src/main.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
config.workspace = true
tracing.workspace = true
utility.workspace = true
futures-util.workspace = true
tokio-tungstenite.workspace = true

[package]
name = "bitwig_nli"
version = "0.1.0"
description = "A tool to get Novation LPProMk3 MIDI Info to a Website for OBS Scene"
license = "Apache-2.0"
readme = "README.md"
keywords = ["utility"]
edition = "2024"

