[dependencies]
toml.workspace = true
serde.workspace = true

[package]
name = "config"
version = "0.1.0"
description = "Config for bwnli"
license = "Apache-2.0"
readme = "README.md"
keywords = ["utility"]
edition = "2024"
