[dependencies]
tracing.workspace = true

[package]
name = "utility"
version = "0.1.0"
description = "Utilities for the Rust program"
license = "Apache-2.0"
readme = "README.md"
keywords = ["utility"]
edition = "2024"
